import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Pixelify_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Montserrat({
  subsets: ["latin"],
});

const pixelify = Pixelify_Sans({
  subsets: ["latin"],
  weight: "400", // Pixelify Sans usually supports 400, 500, 600, 700
  variable: "--font-pixelify", // Optional: for Tailwind usage
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${pixelify.variable}`}>
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
